language: bash
sudo: required
dist: trusty
env:
- SUITE="z3" PATH=$TRAVIS_BUILD_DIR/bin:$PATH
- SUITE="qemu" PATH=$TRAVIS_BUILD_DIR/bin:$PATH
- SUITE="qira" PATH=$TRAVIS_BUILD_DIR/bin:$PATH
- SUITE="afl" PATH=$TRAVIS_BUILD_DIR/bin:$PATH
- SUITE="all" PATH=$TRAVIS_BUILD_DIR/bin:$PATH
install: (sudo apt-get update || true) && bin/manage-tools -s setup
script:
- VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh manage-tools -s -v test $SUITE
