language: bash
sudo: required
dist: trusty
env:
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH SUITE="z3" OPTS="-s -v -f"
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH SUITE="qemu" OPTS="-s -f"
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH SUITE="qira" OPTS="-s -f"
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH SUITE="afl" OPTS="-s -f"
- PATH=$TRAVIS_BUILD_DIR/bin:$PATH SUITE="all" OPTS="-s"
install: (sudo apt-get update || true) && bin/manage-tools -s setup
script:
- VIRTUALENVWRAPPER_SCRIPT=/usr/share/virtualenvwrapper/virtualenvwrapper.sh manage-tools $OPTS test $SUITE
